[package]
name = "docbaygio"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = "3.0.4"
sanitize_html = "0.8.1"
anyhow = "1.0.95"
nanohtml2text = "0.2.1"
epub-builder = "0.7.4"
clap = { version = "4.5.28", features = ["derive"] }
