[package]
name = "docbaygio"
version = "0.1.0"
edition = "2021"

[dependencies]
readability = "0.3.0"
epub-builder = "0.8.0"
url = "2.5.4"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true